import Link from "next/link";
import { notFound } from "next/navigation";
import { requireRole } from "@/lib/auth/require-role";
import { createClient } from "@/lib/supabase/server";
import { ASSIGNMENT_INFO } from "@/lib/assignment-info";
import { ReplyEditor } from "@/app/trainer/(hub)/grade-query-reply/reply-editor";
import { markAppealRaised, markAppealResolved } from "@/app/trainer/(hub)/grade-query-reply/actions";
import type { GradeQueryEvidenceSnapshot } from "@/lib/grade-query-reply";
import type { SubmissionStatus, StandardRating } from "@/lib/supabase/types";
import { StandardRatingPill, SubmissionStatusPill } from "@/lib/status-pill";

// build-spec.md "Grade query -- the reply before an appeal". A single
// generated reply: the frozen evidence snapshot (never re-computed after
// generation -- see migration 0064's header comment) plus the two
// tutor-authored paragraphs, editable until filed and read-only after.
export default async function GradeQueryReplyDetailPage({
  params,
}: {
  params: Promise<{ traineeId: string; replyId: string }>;
}) {
  const { traineeId, replyId } = await params;
  const trainer = await requireRole(["trainer", "admin"]);
  const supabase = await createClient();

  const { data: reply } = await supabase
    .from("grade_query_replies")
    .select("*")
    .eq("id", replyId)
    .eq("trainee_id", traineeId)
    .maybeSingle();

  if (!reply || reply.course_id !== trainer.course_id) {
    notFound();
  }

  const [{ data: trainee }, { data: generatedBy }, { data: filedBy }] = await Promise.all([
    supabase.from("profiles").select("full_name").eq("id", traineeId).maybeSingle(),
    supabase.from("profiles").select("full_name").eq("id", reply.generated_by).maybeSingle(),
    reply.filed_by
      ? supabase.from("profiles").select("full_name").eq("id", reply.filed_by).maybeSingle()
      : Promise.resolve({ data: null }),
  ]);

  const evidence = reply.evidence_snapshot as GradeQueryEvidenceSnapshot;

  return (
    <div className="flex flex-col gap-6">
      <Link href={`/trainer/grade-query-reply/${traineeId}`} className="text-sm text-muted hover:text-primary">
        ← {trainee?.full_name ?? "Candidate"}&apos;s grade query replies
      </Link>

      <div className="sheet flex flex-col gap-1 p-6">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <h1 className="font-serif text-xl text-ink">Grade query reply -- {trainee?.full_name}</h1>
          <span className={`pill ${reply.filed_at ? "pill-success" : "pill-neutral"}`}>
            {reply.filed_at ? "Filed" : "Draft -- not filed"}
          </span>
        </div>
        <p className="text-sm text-muted">
          Generated by {generatedBy?.full_name ?? "--"} on {new Date(reply.generated_at).toLocaleString()}
          {reply.filed_at ? (
            <>
              {" "}
              · filed by {filedBy?.full_name ?? "--"} on {new Date(reply.filed_at).toLocaleString()}
            </>
          ) : null}
        </p>
      </div>

      {/* ---- Grade awarded + descriptors ---- */}
      <div className="sheet flex flex-col gap-3 p-6">
        <h2 className="font-serif text-lg text-ink">Grade awarded</h2>
        <p className="text-sm text-ink">
          {evidence.gradeAwarded ?? "Not yet decided"}
          {evidence.gradeSource === "provisional" ? " (provisional -- final not yet recommended)" : null}
        </p>

        {evidence.descriptorsForGradeAwarded ? (
          <div className="rounded-[6px] border border-border p-3 text-sm">
            <p className="font-medium text-ink">What {evidence.descriptorsForGradeAwarded.grade} requires</p>
            {evidence.descriptorsForGradeAwarded.dimensions ? (
              <div className="mt-2 flex flex-col gap-2">
                {evidence.descriptorsForGradeAwarded.dimensions.map((d) => (
                  <p key={d.name} className="text-muted">
                    <span className="text-ink">{d.name}:</span> {d.text}
                  </p>
                ))}
              </div>
            ) : (
              <p className="mt-2 text-muted">{evidence.descriptorsForGradeAwarded.failText}</p>
            )}
          </div>
        ) : (
          <p className="text-sm text-muted">No performance descriptor applies to this grade (Withdrawn, or no grade set).</p>
        )}

        {evidence.descriptorsForGradeAbove ? (
          <div className="rounded-[6px] border border-border p-3 text-sm">
            <p className="font-medium text-ink">
              What {evidence.descriptorsForGradeAbove.grade} would have required
            </p>
            <div className="mt-2 flex flex-col gap-2">
              {evidence.descriptorsForGradeAbove.dimensions?.map((d) => (
                <p key={d.name} className="text-muted">
                  <span className="text-ink">{d.name}:</span> {d.text}
                </p>
              ))}
            </div>
          </div>
        ) : evidence.gradeAwarded === "Pass A" ? (
          <p className="text-sm text-muted">Pass A is already the highest grade -- there is no grade above it.</p>
        ) : null}

        <details className="text-xs text-muted">
          <summary className="cursor-pointer text-ink">Assignment/eligibility rules that can cap a grade</summary>
          <ul className="mt-2 list-disc pl-5">
            {evidence.eligibilityNotes.map((e) => (
              <li key={e}>{e}</li>
            ))}
          </ul>
        </details>
      </div>

      {/* ---- Teaching practice ---- */}
      <div className="sheet flex flex-col gap-3 p-6">
        <h2 className="font-serif text-lg text-ink">Teaching practice</h2>
        <p className="text-sm text-muted">
          {evidence.tpsTaughtCount} TP lesson{evidence.tpsTaughtCount === 1 ? "" : "s"} taught ·{" "}
          {evidence.hoursAssessedTotal} hours assessed · {evidence.tpsPassedCount} to standard or above
        </p>
        {evidence.tpOutcomes.length > 0 ? (
          <table className="table-plain w-full text-sm">
            <thead>
              <tr>
                <th className="text-muted">TP</th>
                <th className="text-muted">Date taught</th>
                <th className="text-muted">Outcome</th>
              </tr>
            </thead>
            <tbody>
              {evidence.tpOutcomes.map((tp) => (
                <tr key={tp.tpNumber}>
                  <td className="text-ink">TP{tp.tpNumber}</td>
                  <td className="text-muted">{tp.taughtAt ? new Date(tp.taughtAt).toLocaleDateString() : "--"}</td>
                  <td>
                    <StandardRatingPill rating={tp.outcome as StandardRating | null} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <p className="text-sm text-muted">No TP lessons taught yet.</p>
        )}
      </div>

      {/* ---- Criteria ---- */}
      <div className="sheet flex flex-col gap-3 p-6">
        <h2 className="font-serif text-lg text-ink">Criteria met</h2>
        <p className="text-sm text-muted">
          {evidence.criteriaMetCount} of {evidence.criteriaTotal} criteria met ({evidence.criteriaPct}%) --{" "}
          {evidence.criteriaAboveStandardCount} above standard, {evidence.criteriaToStandardCount} to standard,{" "}
          {evidence.criteriaNotYetAssessedCount} not yet assessed.
        </p>
        {evidence.criteriaNotMet.length > 0 ? (
          <div>
            <p className="text-sm font-medium text-ink">Not met (rated &quot;not to standard&quot;):</p>
            <ul className="mt-1 list-disc pl-5 text-sm text-muted">
              {evidence.criteriaNotMet.map((c) => (
                <li key={c.code}>
                  {c.code}: {c.label}
                </li>
              ))}
            </ul>
          </div>
        ) : (
          <p className="text-sm text-muted">No criteria are currently rated &quot;not to standard&quot;.</p>
        )}
      </div>

      {/* ---- Assignments ---- */}
      <div className="sheet flex flex-col gap-3 p-6">
        <h2 className="font-serif text-lg text-ink">Written assignments</h2>
        <p className="text-sm text-muted">
          {evidence.assignmentsNeedingResubmissionCount} of {evidence.assignments.length} needed a resubmission.
        </p>
        {evidence.assignments.length > 0 ? (
          <table className="table-plain w-full text-sm">
            <thead>
              <tr>
                <th className="text-muted">Assignment</th>
                <th className="text-muted">1st submission</th>
                <th className="text-muted">Resubmission</th>
                <th className="text-muted">Grade</th>
              </tr>
            </thead>
            <tbody>
              {evidence.assignments.map((a) => (
                <tr key={a.assignmentType}>
                  <td className="text-ink">
                    {ASSIGNMENT_INFO[a.assignmentType as keyof typeof ASSIGNMENT_INFO]?.title ?? a.assignmentType}
                  </td>
                  <td>
                    <SubmissionStatusPill status={a.firstStatus as SubmissionStatus} />
                  </td>
                  <td className="text-muted">
                    {a.neededResubmission ? (
                      <SubmissionStatusPill status={a.resubmissionStatus as SubmissionStatus} />
                    ) : (
                      "Not required"
                    )}
                  </td>
                  <td className="text-muted">{a.finalGrade ?? "--"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <p className="text-sm text-muted">No assignments on file.</p>
        )}
      </div>

      {/* ---- Tutorials ---- */}
      <div className="sheet flex flex-col gap-3 p-6">
        <h2 className="font-serif text-lg text-ink">Tutorials</h2>
        <div className="flex flex-col divide-y divide-border">
          {evidence.tutorials
            .filter((t) => t.applicable)
            .map((t) => (
              <div key={t.stage} className="flex flex-col gap-1 py-3 text-sm first:pt-0">
                <p className="font-medium text-ink">
                  Stage {t.stage} tutorial -- {t.tutorialGiven ? "given" : "not yet given"}
                  {t.completedAt ? ` · ${new Date(t.completedAt).toLocaleDateString()}` : ""}
                  {t.hoursTaught != null ? ` · ${t.hoursTaught} hours taught` : ""}
                </p>
                {t.tutorOverall ? <StandardRatingPill rating={t.tutorOverall} /> : null}
                {t.notes ? <p className="whitespace-pre-wrap text-muted">{t.notes}</p> : null}
              </div>
            ))}
          {!evidence.tutorials.find((t) => t.stage === 3)?.applicable ? (
            <p className="py-3 text-sm text-muted first:pt-0">Stage 3 tutorial was not required for this candidate.</p>
          ) : null}
        </div>
      </div>

      {/* ---- Letters ---- */}
      <div className="sheet flex flex-col gap-2 p-6">
        <h2 className="font-serif text-lg text-ink">Letters issued</h2>
        <p className="text-sm text-muted">{evidence.lettersIssuedNote}</p>
      </div>

      {/* ---- Provisional slash justification ---- */}
      {evidence.provisionalIsSlashed ? (
        <div className="sheet flex flex-col gap-2 p-6">
          <h2 className="font-serif text-lg text-ink">Provisional grade justification</h2>
          <p className="text-sm text-ink">
            Provisional: {evidence.provisionalGrade}/{evidence.provisionalGradeUpper} (undecided) -- set{" "}
            {evidence.provisionalSetAt ? new Date(evidence.provisionalSetAt).toLocaleDateString() : "--"}
          </p>
          {evidence.provisionalJustification ? (
            <p className="whitespace-pre-wrap text-sm text-muted">{evidence.provisionalJustification}</p>
          ) : (
            <p className="text-sm text-muted">No written justification is on file for this slash yet.</p>
          )}
        </div>
      ) : null}

      {/* ---- Tutor-authored paragraphs / editor ---- */}
      {reply.filed_at ? (
        <div className="sheet flex flex-col gap-4 p-6">
          <h2 className="font-serif text-lg text-ink">Filed reply</h2>
          <div>
            <p className="text-sm font-medium text-ink">What would have made the difference</p>
            <p className="mt-1 whitespace-pre-wrap text-sm text-muted">
              {reply.what_would_have_made_the_difference}
            </p>
          </div>
          <div>
            <p className="text-sm font-medium text-ink">What happens next</p>
            <p className="mt-1 whitespace-pre-wrap text-sm text-muted">{reply.what_happens_next}</p>
          </div>
        </div>
      ) : null}

      {/* ---- Formal appeal flag -- connect-build-specs-5-gaps-2026-08-21.md
          item 5. The appeal itself happens outside Connect; this is just a
          manual record of whether one's open, which close-out blocks on. */}
      {reply.filed_at ? (
        <div className="sheet flex flex-col gap-3 p-6">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h2 className="font-serif text-lg text-ink">Formal appeal</h2>
            <span className={`pill ${reply.appeal_raised_at && !reply.appeal_resolved_at ? "pill-warning" : "pill-neutral"}`}>
              {reply.appeal_raised_at && !reply.appeal_resolved_at ? "Open -- blocks close-out" : reply.appeal_resolved_at ? "Resolved" : "None on record"}
            </span>
          </div>
          <p className="text-sm text-muted">
            Cambridge&apos;s formal appeal process happens entirely outside Connect -- this just records whether the
            candidate has taken this reply to a formal appeal, so close-out knows to wait.
          </p>
          {reply.appeal_raised_at ? (
            <p className="text-xs text-muted">
              Raised {new Date(reply.appeal_raised_at).toLocaleDateString()}
              {reply.appeal_resolved_at ? ` · resolved ${new Date(reply.appeal_resolved_at).toLocaleDateString()}` : ""}
            </p>
          ) : null}
          {reply.appeal_raised_at && !reply.appeal_resolved_at ? (
            <form action={markAppealResolved}>
              <input type="hidden" name="reply_id" value={reply.id} />
              <input type="hidden" name="trainee_id" value={traineeId} />
              <button type="submit" className="self-start rounded-[6px] border border-border px-3.5 py-2 text-sm font-medium text-ink trainer-hover-fill">
                Mark appeal resolved
              </button>
            </form>
          ) : (
            <form action={markAppealRaised}>
              <input type="hidden" name="reply_id" value={reply.id} />
              <input type="hidden" name="trainee_id" value={traineeId} />
              <button type="submit" className="self-start rounded-[6px] border border-border px-3.5 py-2 text-sm font-medium text-ink trainer-hover-fill">
                Mark a formal appeal raised
              </button>
            </form>
          )}
        </div>
      ) : null}

      {!reply.filed_at ? (
        <ReplyEditor
          replyId={reply.id}
          traineeId={traineeId}
          initialWhatWouldHaveMadeTheDifference={reply.what_would_have_made_the_difference ?? ""}
          initialWhatHappensNext={reply.what_happens_next ?? ""}
        />
      ) : null}
    </div>
  );
}
