// design_handoff_open_items_batch, GTKY Activity Bank.dc.html + for-claude-code-gtky-assignment-logic.md.
// Fixed, global reference content -- same convention as assignment-info.ts's
// ASSIGNMENT_INFO, not a DB table: this bank isn't centre-editable ("no
// manual tutor override step by default... an edit to their assignment
// record, not a new screen"), so it lives in code like every other fixed
// content library in this app. Ported programmatically from the mockup's
// own BANK/MODE/ONLINE arrays to avoid retyping 90 entries by hand.
import "server-only";

export type GtkyLevelBand = "a1" | "elem" | "pre" | "inter" | "upper";
export type GtkyMode = "both" | "f2f" | "online";

export interface GtkyActivity {
  slug: string;
  name: string;
  level: GtkyLevelBand;
  meta: string;
  steps: string[];
  /** Tutor-only -- never shown to the candidate or the handout. */
  reveals: string;
  mode: GtkyMode;
  /** Tutor-only online-delivery adaptation note, when it differs from face-to-face. */
  onlineNote: string | null;
}

export const GTKY_BANK: GtkyActivity[] = [
  {
    slug: "ball_game",
    name: "Ball Game",
    level: "a1",
    meta: "Whole class · 20 min · a soft ball, or mime one",
    steps: ["Stand everyone in a circle and say your own name as you throw.", "Whoever catches says their name, then throws to someone else.", "Second round: throw and ask one question — where are you from, what do you do."],
    reveals: "Names, obviously. But also who volunteers to catch and who avoids eye contact — that is your first read on who will speak in class.",
    mode: "f2f",
    onlineNote: null,
  },
  {
    slug: "find_someone_who",
    name: "Find Someone Who",
    level: "elem",
    meta: "Mingle · 20 min · one grid each, printed",
    steps: ["Give everyone the grid: find someone who has a cat, who drives, who likes coffee.", "They stand up and ask each other until every line has a name against it.", "Sit down and check three or four as a class."],
    reveals: "Question formation at its most basic — do you, have you, can you. You will hear exactly which ones collapse.",
    mode: "both",
    onlineNote: "Grid in a shared document everyone can type into. Breakout rooms of three, swapped twice, rather than a free mingle.",
  },
  {
    slug: "line_up_according_to",
    name: "Line Up According To…",
    level: "elem",
    meta: "Whole class · 20 min · nothing",
    steps: ["Ask them to stand in a line by birthday, January at one end, December at the other.", "They have to talk to each other to work out where they go.", "Do it again by the first letter of their name, or how far they travelled today."],
    reveals: "Numbers, months and dates — and it gets everyone moving and talking within ninety seconds, which matters more on day one than anything linguistic.",
    mode: "f2f",
    onlineNote: null,
  },
  {
    slug: "find_your_other_half",
    name: "Find Your Other Half",
    level: "elem",
    meta: "Mingle · 20 min · word-pair cards",
    steps: ["Hand out cards, each with half a familiar pair — salt and pepper, happy and birthday.", "They mingle and find their partner, then sit down together.", "Each pair tells the class their two words."],
    reveals: "Vocabulary they already have, and how they handle not knowing — do they ask, guess, or wait to be found.",
    mode: "both",
    onlineNote: "Send each learner their half by private chat. They post theirs in the main chat and claim their partner, then you pair them into a breakout room.",
  },
  {
    slug: "draw_your_name",
    name: "Draw Your Name",
    level: "elem",
    meta: "Mingle · 20 min · paper and pens",
    steps: ["On the board, draw a picture for each letter of your name — Claire becomes cat, lemon, apple, ice cream, rabbit, envelope.", "Elicit each picture, write the word, circle the first letters, and let them work out your name.", "They do the same for their own name, then mingle showing their drawings while others guess."],
    reveals: "Spelling, initial sounds and vocabulary they already own. Also the quietest activity here, which suits a nervous elementary group.",
    mode: "both",
    onlineNote: "They draw on paper and hold it to the camera, or use the annotate tool on a blank shared screen. Holding paper up is better — it is faster and everyone can see at once.",
  },
  {
    slug: "speaking_corners",
    name: "Speaking Corners",
    level: "elem",
    meta: "Whole class · 20 min · nothing",
    steps: ["Each corner of the room is a type of music — jazz, classical, pop, rock.", "Clap, and everyone moves to the corner that fits them, then explains why to someone else there.", "Stop, take quick feedback, and run it again with seasons, films, or favourite thing about Istanbul."],
    reveals: "Preferences and short justifications, repeated four or five times. You see who talks unprompted and who waits to be asked.",
    mode: "f2f",
    onlineNote: null,
  },
  {
    slug: "star_facts",
    name: "Star Facts",
    level: "inter",
    meta: "Pairs or mingle · 20 min · paper",
    steps: ["Draw a six-pointed star on the board, your name in the middle, one word or number in each point — Mexico, 1978, 2, Emma.", "They ask yes/no questions to work out why each one matters. Were you born in Mexico? Did you live there?", "They draw their own star and do the same with each other."],
    reveals: "Yes/no question forms and auxiliaries, which is where intermediate learners quietly fall apart. Also gives you their biography for free.",
    mode: "both",
    onlineNote: "Draw the star on a shared whiteboard, or hold paper to the camera. Yes/no questions work better online than almost anything else — no crosstalk.",
  },
  {
    slug: "a_minute_of_questions",
    name: "A Minute of Questions",
    level: "inter",
    meta: "Small groups · 20 min · nothing",
    steps: ["Tell them they have one minute to fire as many questions at you as they can — you will not answer yet.", "After the minute, answer the ones you remember or feel like answering.", "Groups of three or four, taking turns, one person listening then responding."],
    reveals: "Question formation at speed, and what they are actually curious about — which is more useful for choosing texts than any needs analysis form.",
    mode: "both",
    onlineNote: "Questions go in the chat rather than shouted, which is quieter but also gives you a transcript of what they wanted to know.",
  },
  {
    slug: "hunt_the_teacher",
    name: "Hunt the Teacher",
    level: "inter",
    meta: "Whole class · 20 min · six paragraphs, printed",
    steps: ["Before the lesson, get a paragraph about themselves from each of your colleagues, plus your own.", "Write true/false statements based on all six, and give them out as a handout.", "Stick the paragraphs round the walls; they get up, read, and check their answers."],
    reveals: "Reading for specific information, and it introduces all six candidates at once — the class meets everyone who will teach them in one activity.",
    mode: "both",
    onlineNote: "Paragraphs in a shared document instead of on walls. They scroll rather than walk, and the true/false handout is a second tab.",
  },
  {
    slug: "mime_your_hobby",
    name: "Mime Your Hobby",
    level: "a1",
    meta: "Whole class · 20 min · nothing",
    steps: ["Mime something you do at the weekend until somebody names it. Cooking. Swimming.", "Each learner mimes theirs; the class calls out guesses in English.", "Write each hobby on the board as it is guessed, and let anyone who does the same put their hand up."],
    reveals: "Verbs of everyday activity, and it produces speech from learners who cannot yet build a sentence — a guess is one word and still counts as talking.",
    mode: "both",
    onlineNote: "Works on camera unchanged and is genuinely funnier — the frame crops the mime, so people over-act. Guesses go in the chat so everyone answers at once.",
  },
  {
    slug: "what_is_in_my_bag",
    name: "What Is in My Bag",
    level: "a1",
    meta: "Whole class · 20 min · their own bag",
    steps: ["Take three things out of your bag one at a time and name each.", "Learners do the same — three objects, named, held up.", "Ask who else has the same. Hands up, and count them out loud together."],
    reveals: "Concrete nouns they need daily, plus numbers when you count the hands. Nothing has to be prepared and nobody has to invent content.",
    mode: "both",
    onlineNote: "Better online, because everyone is at home surrounded by their own things. Ask them to fetch three objects before you start.",
  },
  {
    slug: "the_same_as_me",
    name: "The Same as Me",
    level: "a1",
    meta: "Whole class · 20 min · nothing",
    steps: ["Say a short sentence about yourself. I have a sister. I drink tea. I live near here.", "Anyone the same stands up, or raises a hand if you are online.", "Learners then take turns saying their own sentence and seeing who stands."],
    reveals: "The most controlled possible production — one sentence, modelled, repeated by everyone. You hear each learner say one thing and can already tell who has a verb ending problem.",
    mode: "both",
    onlineNote: "Reaction buttons or hands to the camera instead of standing. Slower to read than a room, so pause a beat longer before moving on.",
  },
  {
    slug: "draw_and_guess",
    name: "Draw and Guess",
    level: "a1",
    meta: "Whole class · 20 min · paper, or a shared whiteboard",
    steps: ["Draw something you like on paper. Food, a place, an animal. No words.", "Hold it up; the class guesses what it is and why you like it.", "Anyone who likes the same thing shows their drawing next to it."],
    reveals: "Vocabulary they recognise before they can produce it, and drawing removes the language barrier entirely for the first two minutes — which for a nervous A1 group is the whole battle.",
    mode: "both",
    onlineNote: "Paper held to the camera beats the annotate tool — faster, and everyone sees all the drawings at once when you ask them to hold up together.",
  },
  {
    slug: "my_name_starts_with",
    name: "My Name Starts With",
    level: "a1",
    meta: "Whole class · 20 min · nothing",
    steps: ["Say your name and one thing you like beginning with the same letter. Ali — apples.", "Go round the circle; each person adds theirs.", "Second time round, see how many pairs the class can remember together."],
    reveals: "The alphabet and initial sounds, which A1 learners mix up constantly, plus names — and the repetition means everyone hears every name four or five times.",
    mode: "both",
    onlineNote: "Go in the order of the participant list so nobody is unsure whose turn it is. Type each pair in the chat as it comes, and the list becomes the class register.",
  },
  {
    slug: "where_are_you_from",
    name: "Where Are You From",
    level: "a1",
    meta: "Whole class · 20 min · a map on screen or on the wall",
    steps: ["Point to where you are from on the map and say the city and country.", "Each learner does the same — pointing is allowed instead of speaking if they need it.", "Ask who is furthest away, who is nearest, and count how many countries the class covers."],
    reveals: "Country and city names, and comparatives introduced by you rather than produced by them. Works with a class that shares no common language at all.",
    mode: "both",
    onlineNote: "Share a map on screen and let them drop annotation pins, or just say the place while you point. Pins are better — a learner who cannot say it can still show it.",
  },
  {
    slug: "numbers_bingo_about_us",
    name: "Numbers Bingo About Us",
    level: "a1",
    meta: "Whole class · 20 min · a grid of numbers, printed or on screen",
    steps: ["Everyone gets a grid of nine numbers between one and thirty.", "Learners take turns saying a number that means something to them — my age, my floor, my bus.", "Cross it off if you have it. First to three in a row calls out."],
    reveals: "Numbers heard and produced with a reason to listen, and every number comes with a fragment of personal information attached.",
    mode: "both",
    onlineNote: "Grid on a shared slide, or they draw their own nine squares on paper. Numbers called out loud, crossed off at home.",
  },
  {
    slug: "picture_of_my_week",
    name: "Picture of My Week",
    level: "a1",
    meta: "Pairs · 20 min · phones",
    steps: ["Show one photo from your phone from the last week and say two words about it.", "Their partner asks one question. Where? Who?", "Swap partners once and do it again with the same photo — it comes out better the second time."],
    reveals: "Real content they care about, minimum language, and the repeat tells you exactly how much they gain from a second attempt — which is useful for the assignment.",
    mode: "both",
    onlineNote: "The strongest A1 online activity in the set — the photo is already on the phone they are holding. Breakout pairs, remade once.",
  },
  {
    slug: "stand_up_if_you_can",
    name: "Stand Up If You Can",
    level: "a1",
    meta: "Whole class · 20 min · nothing",
    steps: ["Say things people might be able to do. I can drive. I can cook. I can swim.", "Anyone who can, stands up or shows a hand.", "Then let learners call out their own — accept two words and help with the rest."],
    reveals: "Can and cannot, which is the first modal an A1 learner needs and the one that unlocks asking for help in class.",
    mode: "both",
    onlineNote: "Hands to camera rather than standing, or the reaction buttons. Ask them to keep the hand up for three seconds so you can count.",
  },
  {
    slug: "show_me_one_thing",
    name: "Show Me One Thing",
    level: "a1",
    meta: "Whole class · 20 min · whatever is on their desk",
    steps: ["Hold up something near you and say two sentences. This is my cup. I drink tea every morning.", "Everyone finds one object and holds it to the camera in turn.", "Second round: someone else asks one question about it. Is it old? Do you use it every day?"],
    reveals: "Concrete vocabulary they actually own, present simple, and — because everyone is holding something up — the first moment nobody is hiding behind a switched-off camera.",
    mode: "both",
    onlineNote: "Designed for the camera — everyone is already sitting next to their own things. In the room it works too, but people have less around them.",
  },
  {
    slug: "numbers_about_me",
    name: "Numbers About Me",
    level: "a1",
    meta: "Whole class · 20 min · the chat box",
    steps: ["Type four numbers about yourself in the chat. 3, 1998, 12, 2.", "Everyone copies the idea and posts their own four numbers.", "Pick one person’s numbers and let the class ask yes/no questions until they work each one out."],
    reveals: "Numbers, ages and dates — the thing A1 learners have drilled and cannot use. Yes/no questions with almost no vocabulary load.",
    mode: "both",
    onlineNote: "The chat box is the whole activity. Everyone posts at once, nobody waits their turn, and you have a written record of every learner’s numbers to come back to.",
  },
  {
    slug: "where_i_am_right_now",
    name: "Where I Am Right Now",
    level: "a1",
    meta: "Whole class · 20 min · their own room",
    steps: ["Show the class one corner of the room you are in and name three things in it.", "Each learner does the same — camera round the room, three things named.", "Anyone who spots something they also have says so."],
    reveals: "Everyday object vocabulary and there is / I have. Also the gentlest possible way to get cameras on, because the camera is pointing away from their face.",
    mode: "online",
    onlineNote: "Online only, and one of the few activities that is genuinely better on Zoom than in a classroom. Ask permission first and let anyone decline without explaining.",
  },
  {
    slug: "three_emojis",
    name: "Three Emojis",
    level: "a1",
    meta: "Whole class · 20 min · the chat box",
    steps: ["Post three emojis in the chat that say something about you. Nothing else.", "Everyone posts theirs. Read them all out loud.", "Take one person at a time — the class guesses why, in English, and they say yes or no."],
    reveals: "Almost no language to produce, a great deal of language to understand. Works with a group who genuinely cannot form a sentence yet, and they still end up talking.",
    mode: "both",
    onlineNote: "Chat box. Everyone posts simultaneously, which removes the turn-taking that makes A1 learners freeze.",
  },
  {
    slug: "thumbs_up_thumbs_down",
    name: "Thumbs Up, Thumbs Down",
    level: "a1",
    meta: "Whole class · 20 min · reactions",
    steps: ["Say a short sentence. I like coffee. I get up early. I have a cat.", "Everyone shows thumbs up or thumbs down — the reaction button or their actual hand.", "Pick one person each round and ask why, and accept two words as an answer."],
    reveals: "Listening comprehension with a visible answer, so you can see instantly who understood. The best diagnostic in the set for a true beginner group.",
    mode: "both",
    onlineNote: "Reaction buttons, or hands to the camera. Reactions are faster to read but hands are more fun — let them use either.",
  },
  {
    slug: "true_or_false",
    name: "True or False",
    level: "inter",
    meta: "Mingle · 20 min · a slip of paper each",
    steps: ["Everyone writes three sentences about themselves — two true, one false.", "They mingle, read their sentences out, and the other person guesses the lie.", "Keep going until they have spoken to at least six people."],
    reveals: "Past simple and present simple under pressure, and vocabulary they reach for when describing their own life.",
    mode: "both",
    onlineNote: "Breakout rooms of three or four rather than a mingle. Fewer partners, so ask for four sentences instead of three.",
  },
  {
    slug: "onion_rings",
    name: "Onion Rings",
    level: "inter",
    meta: "Two circles · 20 min · nothing",
    steps: ["Two circles, inner facing outer, everyone with a partner.", "Give a topic — what you did last night — and they talk for one minute.", "Outer circle moves one place left, new partner, new topic. Repeat six times."],
    reveals: "Fluency across six short bursts. You hear the same person start six times, which shows what they can produce without preparation.",
    mode: "both",
    onlineNote: "Breakout pairs, remade every ninety seconds. Zoom will re-randomise pairs for you, so the rotation is one click rather than a circle shuffling.",
  },
  {
    slug: "3_things_in_common",
    name: "3 Things in Common",
    level: "inter",
    meta: "Mingle · 20 min · nothing",
    steps: ["They must find two people with whom they share three things.", "Not age, nationality or hair colour — hobbies, where they live, what they studied.", "When they have found them, they sit together as a group."],
    reveals: "Real conversation rather than a drill, and it forms the pairs and groups you will use for the rest of the day.",
    mode: "both",
    onlineNote: "Breakout rooms of three. They report their three in the main chat, which also gives you a written record of the whole class in two minutes.",
  },
  {
    slug: "2_minute_topics",
    name: "2-Minute Topics",
    level: "inter",
    meta: "Small groups · 20 min · topic cards",
    steps: ["Four or five per table, cards face down in the middle — family, music, food, travel.", "One person turns a card and the group talks about it for two minutes.", "Next person, next card, until the cards run out."],
    reveals: "Which topics they open up on and which they shut down. Useful for choosing texts and tasks later.",
    mode: "both",
    onlineNote: "Topics on a shared slide, one breakout room per group, and a timer on screen so nobody has to watch the clock.",
  },
  {
    slug: "call_my_bluff",
    name: "Call My Bluff",
    level: "upper",
    meta: "Teams · 20 min · three unusual words",
    steps: ["Each team gets an unusual word and writes three definitions — one true, two invented.", "They read all three out, straight-faced, and the other team votes.", "A point for guessing right, a point for fooling them."],
    reveals: "Register and hedging — the language of sounding confident about something you do not know, which upper-intermediate learners consistently lack.",
    mode: "both",
    onlineNote: "Teams in breakout rooms to write their definitions, then back to the main room to perform. Voting by reaction or in the chat.",
  },
  {
    slug: "just_a_minute",
    name: "Just a Minute",
    level: "upper",
    meta: "Whole class · 20 min · a timer",
    steps: ["One person speaks on a topic for sixty seconds.", "No hesitation, no repetition, no going off the subject.", "Anyone can challenge; if the challenge is fair they take over the topic."],
    reveals: "Hesitation, fillers and self-correction all made audible on purpose. A goldmine for the assignment, and genuinely funny.",
    mode: "both",
    onlineNote: "Works unchanged, and arguably better — the timer is on screen and challenges come through the chat, so the interruption is visible without anybody shouting.",
  },
  {
    slug: "question_swap",
    name: "Question Swap",
    level: "upper",
    meta: "Mingle · 20 min · a card each",
    steps: ["Everyone writes one interesting question on a card — not yes or no.", "Ask your question, answer theirs, then swap cards and find someone new.", "Keep swapping so each question travels around the room."],
    reveals: "Question formation at a level where it usually goes wrong — indirect questions, tenses in the second clause.",
    mode: "both",
    onlineNote: "Questions in the chat, then paired breakouts. The swap is you re-randomising the rooms.",
  },
  {
    slug: "five_points_about_me",
    name: "Five Points About Me",
    level: "upper",
    meta: "Pairs · 20 min · a sheet each",
    steps: ["Write one word in each corner of the page and one in the middle — five things that matter to you.", "Swap with a partner, who has to guess why each one is there by asking questions.", "Then swap partners and do it again with the same page."],
    reveals: "Explanation and justification, told twice — the second telling is always more fluent, which is worth pointing out to them.",
    mode: "both",
    onlineNote: "Paper to camera or a shared slide each. Pairs in breakout rooms, remade once so they tell it twice.",
  },
  {
    slug: "colour_of_my_day",
    name: "Colour of My Day",
    level: "a1",
    meta: "Whole class · 20 min · nothing",
    steps: ["Say a colour and one word about why. Blue — sea.", "Each learner gives their colour and their word.", "Group everyone by colour and see who chose the same."],
    reveals: "Colours and simple nouns, with a reason attached so it is not a vocabulary drill.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "point_and_name",
    name: "Point and Name",
    level: "a1",
    meta: "Whole class · 20 min · the room, or their room",
    steps: ["Point at five things and name them together as a class.", "Learners take turns pointing at something and naming it.", "Anything nobody knows goes on the board — that is the class’s first word list."],
    reveals: "What they can and cannot name in a room, which is the fastest vocabulary diagnostic there is.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "yes_no_maybe",
    name: "Yes, No, Maybe",
    level: "a1",
    meta: "Whole class · 20 min · three cards each",
    steps: ["Everyone holds three cards: yes, no, maybe.", "Ask simple questions. Do you like coffee? Do you drive?", "They hold up a card, then you ask one person to say a word about why."],
    reveals: "Comprehension with a visible answer, and maybe gives cautious learners somewhere to stand.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "two_lies_and_a_truth",
    name: "Two Lies and a Truth",
    level: "elem",
    meta: "Small groups · 20 min · paper",
    steps: ["Write three short sentences about yourself — two false, one true.", "Read them to your group; they ask questions and guess the true one.", "Each group reports the best lie to the class."],
    reveals: "Present and past simple in very short sentences, and question forms in the guessing.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "my_weekend_in_three_pictures",
    name: "My Weekend in Three Pictures",
    level: "elem",
    meta: "Pairs · 20 min · phones or drawings",
    steps: ["Choose three photos, or draw three quick pictures, of your last weekend.", "Show your partner and say one sentence about each.", "Swap partners and do it again."],
    reveals: "Past simple with concrete support, and the second telling shows what they retain.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "guess_my_job",
    name: "Guess My Job",
    level: "elem",
    meta: "Whole class · 20 min · nothing",
    steps: ["Mime or describe your job without naming it.", "The class asks yes/no questions until they get it.", "Write each job on the board as it is guessed."],
    reveals: "Work vocabulary, which every adult class needs on day one, plus yes/no question forms.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "food_i_love_food_i_hate",
    name: "Food I Love, Food I Hate",
    level: "elem",
    meta: "Mingle · 20 min · nothing",
    steps: ["Say one food you love and one you cannot stand.", "Mingle and find someone who agrees with you about either.", "Report the strangest disagreement to the class."],
    reveals: "Like and dislike structures, and it produces genuine argument in a way nothing else at this level does.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "classroom_survey",
    name: "Classroom Survey",
    level: "elem",
    meta: "Mingle · 20 min · a question each",
    steps: ["Everyone writes one question they will ask the whole class.", "Mingle, ask everyone, keep a tally.", "Report your results as numbers. Six people drive. Four people have a cat."],
    reveals: "Question forms and numbers together, and the tally gives you a written record of the class.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "my_favourite_place",
    name: "My Favourite Place",
    level: "elem",
    meta: "Pairs · 20 min · nothing",
    steps: ["Describe a place you love without naming it. Where is it? What can you see?", "Your partner guesses the kind of place — beach, city, village.", "Swap and repeat, then tell the class about your partner’s place."],
    reveals: "Descriptive vocabulary and there is / there are, plus reporting in the third person at the end.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "the_day_in_order",
    name: "The Day in Order",
    level: "elem",
    meta: "Pairs · 20 min · slips of paper",
    steps: ["Write five things you did yesterday on separate slips, out of order.", "Your partner puts them in order by asking questions.", "Check together and see who got closest."],
    reveals: "Past simple and time expressions, with the ordering doing the work rather than a gap-fill.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "who_is_it",
    name: "Who Is It",
    level: "elem",
    meta: "Whole class · 20 min · paper",
    steps: ["Everyone writes three sentences describing themselves — no names.", "Collect, shuffle, redistribute.", "Read one out; the class guesses who wrote it."],
    reveals: "Descriptive language and listening, and it is the quietest way to hear every learner’s writing at once.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "shopping_list_memory",
    name: "Shopping List Memory",
    level: "elem",
    meta: "Whole class · 20 min · nothing",
    steps: ["I went to the market and I bought bread.", "Each person repeats everything before them and adds one item.", "See how far round the class you get before it collapses."],
    reveals: "Food vocabulary, past simple of buy, and memory pressure that reveals who is quietly lost.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "would_you_rather",
    name: "Would You Rather",
    level: "elem",
    meta: "Two sides of the room · 20 min · nothing",
    steps: ["Would you rather live in a city or the countryside? Move to one side.", "Talk to someone on your side about why.", "Two people from each side report back."],
    reveals: "Preference and simple justification, with movement doing the choosing so nobody has to speak first.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "find_the_fib",
    name: "Find the Fib",
    level: "elem",
    meta: "Small groups · 20 min · nothing",
    steps: ["Your group agrees three facts about one member — two true, one invented.", "Present them to the class as a group.", "The class votes on the invention."],
    reveals: "Third-person forms, which elementary learners drop constantly, and the group prep means nobody is exposed alone.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "alphabet_race",
    name: "Alphabet Race",
    level: "elem",
    meta: "Teams · 20 min · board or shared doc",
    steps: ["Give a category — food, jobs, places.", "Teams race to write one word for as many letters of the alphabet as they can.", "Read out and score; a wrong spelling scores nothing."],
    reveals: "Vocabulary breadth and spelling under time pressure, and the arguments are in English.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "family_in_five_words",
    name: "Family in Five Words",
    level: "elem",
    meta: "Pairs · 20 min · paper",
    steps: ["Write five words about your family. Names, jobs, places, numbers.", "Your partner asks questions to work out what each word means.", "Introduce your partner’s family to the class."],
    reveals: "Family vocabulary and possessives, and the reporting stage forces a change of person.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "my_three_firsts",
    name: "My Three Firsts",
    level: "pre",
    meta: "Pairs · 20 min · nothing",
    steps: ["Tell your partner about your first job, your first trip abroad and your first English lesson.", "They ask two questions about whichever interests them most.", "Swap, then tell the class your partner’s best first."],
    reveals: "Past simple across three short narratives, with the reporting stage forcing third person.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "ranking_pyramid",
    name: "Ranking Pyramid",
    level: "pre",
    meta: "Pairs then fours · 20 min · a list of five",
    steps: ["Rank five things that make a good teacher, best at the top.", "Compare with a partner and agree one ranking between you.", "Join another pair and agree again."],
    reveals: "Comparatives and agreeing language, with the pressure rising each time the group doubles.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "guess_the_photo",
    name: "Guess the Photo",
    level: "pre",
    meta: "Pairs · 20 min · phones",
    steps: ["Choose a photo on your phone but do not show it.", "Describe it until your partner can draw or describe it back.", "Show the photo and compare."],
    reveals: "Present continuous and prepositions of place, with an immediate check on whether the description worked.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "weekend_plans_mingle",
    name: "Weekend Plans Mingle",
    level: "pre",
    meta: "Mingle · 20 min · nothing",
    steps: ["Everyone thinks of two things they are doing this weekend.", "Mingle and find someone doing something similar.", "Report the most unusual plan you heard."],
    reveals: "Present continuous for future and going to, which pre-intermediate learners use interchangeably and shouldn’t.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "question_dice",
    name: "Question Dice",
    level: "pre",
    meta: "Small groups · 20 min · one dice per group",
    steps: ["Each number on the dice is a question type — where, when, who, why, what, how.", "Roll, then ask anyone in the group a question starting with that word.", "Keep going until everyone has asked four."],
    reveals: "Question words in isolation, which is where the errors are — why questions with no auxiliary, how questions with no adjective.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "what_happened_next",
    name: "What Happened Next",
    level: "pre",
    meta: "Whole class · 20 min · nothing",
    steps: ["Start a story about your journey to class today. Stop after one sentence.", "The next person adds a sentence, and so on round the room.", "When it gets silly, start again with someone else’s journey."],
    reveals: "Past simple and sequencing words, and the chain means nobody speaks for more than ten seconds.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "my_perfect_day",
    name: "My Perfect Day",
    level: "pre",
    meta: "Pairs · 20 min · nothing",
    steps: ["Describe your perfect day from waking up to going to bed.", "Your partner asks about anything they would change.", "Find one thing you would both do."],
    reveals: "Present simple routines plus would, and a natural bridge into conditionals without teaching them.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "two_countries",
    name: "Two Countries",
    level: "pre",
    meta: "Pairs · 20 min · nothing",
    steps: ["Name three differences between where you grew up and where you live now.", "Your partner asks which you prefer and why.", "Report one difference to the class."],
    reveals: "Comparatives with real content, and it works just as well when both learners are from the same city.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "advice_corner",
    name: "Advice Corner",
    level: "pre",
    meta: "Small groups · 20 min · paper",
    steps: ["Write one small problem on a slip. I always forget vocabulary.", "Swap slips around the group; everyone gives advice.", "Read out the best advice you received."],
    reveals: "Should and could, and the problems tell you what they think is wrong with their own English.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "memory_lane",
    name: "Memory Lane",
    level: "pre",
    meta: "Pairs · 20 min · phones or description",
    steps: ["Describe a photo from your childhood, or find one on your phone.", "Your partner asks three questions about it.", "Say one thing that has changed since."],
    reveals: "Past simple and used to, and the change question opens present perfect naturally.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "would_you_ever",
    name: "Would You Ever",
    level: "pre",
    meta: "Mingle · 20 min · nothing",
    steps: ["Think of three things you would never do. Skydiving. Eating snails.", "Mingle and find someone who has done one of them.", "Report the bravest thing you found."],
    reveals: "Present perfect for experience against would for hypothesis, side by side, which is exactly the pair that confuses them.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "class_records",
    name: "Class Records",
    level: "pre",
    meta: "Whole class · 20 min · nothing",
    steps: ["Find who has travelled furthest, studied English longest, has the most siblings.", "Everyone asks everyone, then the class agrees each record.", "Write the records on the board."],
    reveals: "Superlatives and present perfect, produced by the task rather than drilled.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "the_ideal_flatmate",
    name: "The Ideal Flatmate",
    level: "pre",
    meta: "Small groups · 20 min · nothing",
    steps: ["Name four qualities of a good flatmate.", "Agree the four most important as a group.", "Present to the class and see which group is strictest."],
    reveals: "Adjectives of personality and agreeing language, with a topic that produces genuine strong opinions.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "before_and_after",
    name: "Before and After",
    level: "pre",
    meta: "Pairs · 20 min · nothing",
    steps: ["Think of one thing that changed your daily life — a job, a move, a child.", "Describe how life was before and how it is now.", "Your partner asks whether it was for the better."],
    reveals: "Used to against present simple, which is the cleanest contrast available at this level.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "job_interview_lite",
    name: "Job Interview Lite",
    level: "pre",
    meta: "Pairs · 20 min · nothing",
    steps: ["Interview your partner for a job they would hate.", "Three questions only, and they must answer seriously.", "Decide whether you would hire them and say why."],
    reveals: "Question forms and short justifications, with the absurd premise removing the anxiety of a real interview.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "spot_the_liar",
    name: "Spot the Liar",
    level: "pre",
    meta: "Small groups · 20 min · nothing",
    steps: ["Everyone tells a short story about themselves — true or invented.", "The group asks three questions before voting.", "Liars who survive get a point."],
    reveals: "Sustained past narrative under questioning, which is where invented detail falls apart grammatically.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "six_things_in_the_room",
    name: "Six Things in the Room",
    level: "pre",
    meta: "Whole class · 20 min · the room",
    steps: ["Name six things in this room you would not find in a classroom at home.", "Compare with two other people.", "Agree the three most surprising as a class."],
    reveals: "Object vocabulary plus comparison, and it surfaces cultural difference on the first day without asking about it directly.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "the_recommendation",
    name: "The Recommendation",
    level: "pre",
    meta: "Mingle · 20 min · nothing",
    steps: ["Think of one thing you would recommend to a visitor — a place, a dish, a habit.", "Mingle and collect three recommendations from others.", "Report the one you will actually try."],
    reveals: "Recommending and reasons, and it gives the class a shared list to come back to later in the course.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "desert_island_three",
    name: "Desert Island Three",
    level: "inter",
    meta: "Small groups · 20 min · nothing",
    steps: ["Name three things you would take to a desert island and why.", "Groups compare and agree on the three best choices.", "Each group defends its list to the class."],
    reveals: "Justification and disagreement, and you hear which learners can hold a position under mild pressure.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "the_interview_swap",
    name: "The Interview Swap",
    level: "inter",
    meta: "Pairs · 20 min · nothing",
    steps: ["Interview your partner for four minutes — anything you like.", "Swap and be interviewed.", "Introduce your partner to the class as though they were famous."],
    reveals: "Question forms, then reported speech and third person in the introduction. Two grammar areas from one activity.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "my_life_in_six_objects",
    name: "My Life in Six Objects",
    level: "inter",
    meta: "Pairs · 20 min · nothing",
    steps: ["Name six objects that tell the story of your life.", "Your partner asks about each one until they understand why it matters.", "Report the most surprising object to the class."],
    reveals: "Narrative past and explanation, with the objects preventing the vagueness this kind of task usually produces.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "common_ground_race",
    name: "Common Ground Race",
    level: "inter",
    meta: "Small groups · 20 min · a timer",
    steps: ["In four minutes, find as many things as you can that everyone in your group has in common.", "Nothing visible — not gender, age or nationality.", "Longest genuine list wins; the class can challenge any item."],
    reveals: "Rapid question forms under time pressure, and the challenge round produces real argument.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "two_sides",
    name: "Two Sides",
    level: "inter",
    meta: "Two lines · 20 min · nothing",
    steps: ["Two lines facing each other. Give a statement — homework is useless.", "One line argues for, one against, for ninety seconds.", "Lines shift one place, new partner, new statement, swap sides."],
    reveals: "Agreeing and disagreeing, repeated against several partners so you hear the same learner argue both ways.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "guess_who_wrote_it",
    name: "Guess Who Wrote It",
    level: "inter",
    meta: "Whole class · 20 min · paper",
    steps: ["Everyone writes one unusual sentence about their life.", "Collect, shuffle, and read each aloud.", "The class questions three suspects before guessing."],
    reveals: "Written production you can read afterwards, plus questioning strategies in the guessing round.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "time_capsule",
    name: "Time Capsule",
    level: "inter",
    meta: "Small groups · 20 min · paper",
    steps: ["Your group chooses five things to put in a capsule opened in fifty years.", "Agree on all five — no vetoes without a reason.", "Present and justify to the class."],
    reveals: "Negotiating language and future forms, and the veto rule forces full sentences rather than nodding.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "the_story_of_my_name",
    name: "The Story of My Name",
    level: "inter",
    meta: "Small groups · 20 min · nothing",
    steps: ["Tell the group where your name comes from and whether you like it.", "Anyone with a similar story says so.", "Report the best story to the class."],
    reveals: "Personal narrative with genuine content, and it works in a multilingual group where little else does.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "bucket_list_bingo",
    name: "Bucket List Bingo",
    level: "inter",
    meta: "Mingle · 20 min · a grid each",
    steps: ["Write six things you want to do one day in a grid.", "Mingle and find someone who wants the same, or has already done it.", "Cross off as you go; first to four calls out."],
    reveals: "Want to and present perfect together, which is exactly the pair intermediate learners confuse.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "fact_or_opinion",
    name: "Fact or Opinion",
    level: "inter",
    meta: "Whole class · 20 min · statement cards",
    steps: ["Read out a statement about the city, the language, the weather.", "Learners decide whether it is fact or opinion and say why.", "They write two of their own and try them on the class."],
    reveals: "Hedging and certainty language, and it surfaces cultural assumptions worth knowing about early.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "speed_friending",
    name: "Speed Friending",
    level: "inter",
    meta: "Rotating pairs · 20 min · a timer",
    steps: ["Three minutes per pair. One question each, then free conversation.", "Rotate on the bell — five rounds.", "Each person names one thing they learned about each partner."],
    reveals: "Fluency across repeated fresh starts, and the recall at the end tests listening rather than speaking.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "devil_s_advocate",
    name: "Devil’s Advocate",
    level: "upper",
    meta: "Pairs · 20 min · nothing",
    steps: ["State an opinion you genuinely hold.", "Your partner argues the opposite as convincingly as they can.", "Swap, then say which argument was hardest to answer."],
    reveals: "Concession and counter-argument, which is where upper-intermediate fluency usually stalls.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "the_unpopular_opinion",
    name: "The Unpopular Opinion",
    level: "upper",
    meta: "Whole class · 20 min · nothing",
    steps: ["Everyone offers one mild opinion they expect the room to disagree with.", "Anyone who agrees stands with them.", "The largest minority defends itself."],
    reveals: "Hedging, softening and polite disagreement, all under real social pressure rather than simulated.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "alibi",
    name: "Alibi",
    level: "upper",
    meta: "Pairs then class · 20 min · nothing",
    steps: ["In pairs, invent where you both were last night. Agree the details.", "Separate the pair; the class questions each one alone.", "Compare answers and find the contradictions."],
    reveals: "Past continuous and past simple in sustained narrative, and the contradictions are always in the tenses.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "six_degrees",
    name: "Six Degrees",
    level: "upper",
    meta: "Small groups · 20 min · nothing",
    steps: ["Find a connection between two people in your group in as few steps as possible.", "The connection must be real and explained aloud.", "Shortest genuine chain wins."],
    reveals: "Relative clauses, which upper-intermediate learners avoid rather than get wrong.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "three_headlines",
    name: "Three Headlines",
    level: "upper",
    meta: "Small groups · 20 min · nothing",
    steps: ["Write three headlines that could describe your life so far.", "Your group asks about each one.", "Choose the group’s best headline and explain it to the class."],
    reveals: "Compression and register — headlines force choices about what matters, which is harder than it sounds.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "life_advice",
    name: "Life Advice",
    level: "upper",
    meta: "Mingle · 20 min · paper",
    steps: ["Write one piece of advice you were given and never took.", "Mingle and find someone who was given something similar.", "Report whether either of you should have listened."],
    reveals: "Third conditional and regret structures, arrived at through content rather than a grammar exercise.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "the_missing_year",
    name: "The Missing Year",
    level: "upper",
    meta: "Pairs · 20 min · nothing",
    steps: ["Choose one year of your life and describe it without saying which year.", "Your partner works out roughly when it was and what changed.", "Swap and repeat."],
    reveals: "Narrative tense control across a long turn, which is where fluency and accuracy start competing.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "persuade_me",
    name: "Persuade Me",
    level: "upper",
    meta: "Pairs · 20 min · a timer",
    steps: ["Two minutes to persuade your partner that your city, food or team is better.", "Your partner must be genuinely persuaded or say why not.", "Report the most convincing argument you heard."],
    reveals: "Persuasive register and emphasis, and the requirement to concede makes it a conversation rather than a speech.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "what_would_you_change",
    name: "What Would You Change",
    level: "upper",
    meta: "Small groups · 20 min · nothing",
    steps: ["Name one thing you would change about the place you live.", "The group decides which change would matter most.", "Defend the choice to the class."],
    reveals: "Second conditional and prioritising language, and the group stage forces comparison rather than a list.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "cultural_iceberg",
    name: "Cultural Iceberg",
    level: "upper",
    meta: "Small groups · 20 min · nothing",
    steps: ["Name three things visitors notice about your country and three they never do.", "Compare across the group.", "Report the most surprising invisible one."],
    reveals: "Abstract description, and in a multinational class it produces the best conversation of the day.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "the_turning_point",
    name: "The Turning Point",
    level: "upper",
    meta: "Pairs · 20 min · nothing",
    steps: ["Describe a small decision that changed something big.", "Your partner asks what would have happened otherwise.", "Swap, then tell the class about your partner’s."],
    reveals: "Third conditional and reported speech together, with content strong enough that they forget to be careful.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "job_swap",
    name: "Job Swap",
    level: "upper",
    meta: "Pairs · 20 min · nothing",
    steps: ["Explain your job to your partner well enough that they could do it badly.", "They explain it back; you correct them.", "They introduce themselves to the class as you."],
    reveals: "Explanation, correction and register shift, plus vocabulary from a field nobody else in the room knows.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "two_minute_debate",
    name: "Two-Minute Debate",
    level: "upper",
    meta: "Teams · 20 min · a timer",
    steps: ["Two teams, one motion, two minutes each way.", "No preparation time — the motion is announced as you start.", "The class votes, then argues about the vote."],
    reveals: "Spontaneous structured argument, which is the hardest thing on this list and the most revealing.",
    mode: "both",
    onlineNote: null,
  },
  {
    slug: "hypotheticals",
    name: "Hypotheticals",
    level: "upper",
    meta: "Mingle · 20 min · question cards",
    steps: ["Take a card. If you could live in any decade, which?", "Ask three people, then answer it yourself.", "Find the two people whose answers were furthest apart and let them argue."],
    reveals: "Second conditional across many short turns rather than one long one, so you hear it repeatedly from everyone.",
    mode: "both",
    onlineNote: null,
  },
];

// for-claude-code-gtky-assignment-logic.md: "two real bands -- beginner/
// elementary is one band, pre-intermediate through upper-intermediate is
// the other. A candidate's activities come from their own band's pool."
// Mirrors the mockup's own near()/HIGH logic exactly.
const HIGH_BAND: GtkyLevelBand[] = ["pre", "inter", "upper"];

export function gtkyLevelsAreNear(activityLevel: GtkyLevelBand, targetLevel: GtkyLevelBand): boolean {
  const activityHigh = HIGH_BAND.includes(activityLevel);
  const targetHigh = HIGH_BAND.includes(targetLevel);
  return activityHigh === targetHigh;
}

export function gtkyActivityEligibleForMode(activity: GtkyActivity, courseMode: "f2f" | "online"): boolean {
  return activity.mode === "both" || activity.mode === courseMode;
}

// tp_coursebooks.level is a free string built from levels.ts's LEVEL_OPTIONS
// ("Beginner (A1)", "Upper-Intermediate (B2)", ...) -- the bank's five bands
// don't have their own Advanced/Proficiency content, so C1/C2 fall into the
// nearest available band (upper) rather than having nothing to offer.
const CEFR_CODE_TO_BAND: Record<string, GtkyLevelBand> = {
  A1: "a1",
  A2: "elem",
  "A2+": "pre",
  B1: "inter",
  B2: "upper",
  C1: "upper",
  C2: "upper",
};

export function gtkyLevelBandFromCourseLevel(level: string): GtkyLevelBand | null {
  // tp_coursebooks.level is stored as a bare CEFR code ("A2+", "B1") --
  // confirmed live, not the "(CODE)"-wrapped display format some other
  // screens build around it (e.g. admin/coursebooks/[id]/page.tsx's own
  // "{title} ({level})"). Trim/uppercase defensively rather than assume
  // callers always pass it exactly as stored.
  const code = level.trim().toUpperCase();
  return CEFR_CODE_TO_BAND[code] ?? null;
}
