import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import fs from "fs";
const env = fs.readFileSync(".env.local", "utf8");
const db = createClient(env.match(/NEXT_PUBLIC_SUPABASE_URL=(.+)/)[1].trim(), env.match(/SUPABASE_SERVICE_ROLE_KEY=(.+)/)[1].trim());
const BASE = "https://celta-connect.vercel.app";
const fol = JSON.parse(fs.readFileSync(".walk/picks.json","utf8")).find(p=>p.assignment_type==="Focus on Learner" && p.first_status==="approved");
const b = await chromium.launch();
const page = await (await b.newContext({ timezoneId:"Europe/Istanbul" })).newPage();
const { data: l } = await db.auth.admin.generateLink({ type:"magiclink", email: fol.who.email });
await page.goto(`${BASE}/auth/confirm?token_hash=${l.properties.hashed_token}&type=magiclink&next=%2Fportfolio%2F${fol.trainee_id}%2Fassignments%2F${fol.id}`, { waitUntil:"domcontentloaded" });
await page.waitForTimeout(6000);
const t = await page.evaluate(()=>document.body.innerText);
const show = (label, re) => { const m = t.match(re); console.log(label.padEnd(26), m ? JSON.stringify(m[0].slice(0,110)) : "-- NOT SHOWN --"); };
console.log("CANDIDATE VIEW —", fol.who.full_name, "· Focus on the Learner · approved\n");
show("result banner", /(Passed[^\n]*|Not passed[^\n]*)/);
show("per-criterion marks", /(Met · round 1|Not met · round 1)/);
show("tutor overall comment", /Before you start[\s\S]{0,140}/);
show("tutor section comment", /Your tutor, on this section[^\n]*\n[^\n]{0,90}/);
show("appendices", /Appendix 1[^\n]{0,60}/);
show("cover sheet export", /Export cover sheet[^\n]*/);
console.log("\n--- 'Marked against' block as the candidate sees it ---");
const i = t.indexOf("MARKED AGAINST");
console.log(t.slice(i, i+420));
await b.close();
