import { createClient } from "@supabase/supabase-js";
import fs from "fs";
const env = fs.readFileSync(".env.local", "utf8");
const db = createClient(env.match(/NEXT_PUBLIC_SUPABASE_URL=(.+)/)[1].trim(), env.match(/SUPABASE_SERVICE_ROLE_KEY=(.+)/)[1].trim());
const fol = JSON.parse(fs.readFileSync(".walk/picks.json","utf8")).find(p=>p.assignment_type==="Focus on Learner" && p.first_status==="approved");
const { data: a } = await db.from("assignments").select("first_overall_comment,first_status,first_criteria_marks").eq("id", fol.id).single();
console.log("first_status:", a.first_status);
console.log("first_overall_comment:", a.first_overall_comment ? JSON.stringify(a.first_overall_comment.slice(0,100)) : "*** NULL ***");
const { data: r } = await db.from("assignment_section_responses").select("section_key,first_comments").eq("assignment_id", fol.id);
for (const x of r) console.log("  ", x.section_key.padEnd(24), x.first_comments ? JSON.stringify(x.first_comments.slice(0,70)) : "*** NULL ***");
