import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import fs from "fs";
const env = fs.readFileSync(".env.local", "utf8");
const db = createClient(env.match(/NEXT_PUBLIC_SUPABASE_URL=(.+)/)[1].trim(), env.match(/SUPABASE_SERVICE_ROLE_KEY=(.+)/)[1].trim());
const picks = JSON.parse(fs.readFileSync(".walk/picks.json","utf8"));
const sk = picks.find(p=>p.assignment_type==="Skills");
const b = await chromium.launch();
const page = await (await b.newContext({ timezoneId: "Europe/Istanbul" })).newPage();
const out = [];
page.on("console", m => out.push(`[${m.type()}] ${m.text()}`));
page.on("pageerror", e => out.push("PAGEERROR " + String(e)));
const { data: l } = await db.auth.admin.generateLink({ type:"magiclink", email: sk.who.email });
await page.goto(`http://localhost:3000/auth/confirm?token_hash=${l.properties.hashed_token}&type=magiclink&next=%2Fportfolio%2F${sk.trainee_id}%2Fassignments`, { waitUntil:"domcontentloaded", timeout:180000 });
await page.waitForTimeout(25000);
out.length = 0;
await page.goto(`http://localhost:3000/portfolio/${sk.trainee_id}/assignments/${sk.id}`, { waitUntil:"domcontentloaded", timeout:180000 });
await page.waitForTimeout(30000);
const hits = out.filter(o=>/hydrat|did not match|418|tree hydrated/i.test(o));
console.log(hits.length ? hits.join("\n\n").slice(0,5000) : "(no hydration message)\n" + out.slice(0,6).join("\n"));
await b.close();
