import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import fs from "fs";
const env = fs.readFileSync(".env.local", "utf8");
const db = createClient(env.match(/NEXT_PUBLIC_SUPABASE_URL=(.+)/)[1].trim(), env.match(/SUPABASE_SERVICE_ROLE_KEY=(.+)/)[1].trim());
const BASE = "https://celta-connect.vercel.app";
const picks = JSON.parse(fs.readFileSync(".walk/picks.json","utf8"));
const sk = picks.find(p=>p.assignment_type==="Skills");
const b = await chromium.launch();
const ctx = await b.newContext({ timezoneId: "Europe/Istanbul" });
const page = await ctx.newPage();
const errs = [];
page.on("pageerror", e => errs.push("PAGEERROR " + String(e).slice(0,300)));
page.on("console", m => { if (m.type()==="error") errs.push(`[${m.type()}] ` + m.text().slice(0,300)); });
page.on("requestfailed", r => errs.push("REQFAIL " + r.url().slice(0,110) + " " + (r.failure()?.errorText??"")));
const { data: l } = await db.auth.admin.generateLink({ type:"magiclink", email: sk.who.email });
await page.goto(`${BASE}/auth/confirm?token_hash=${l.properties.hashed_token}&type=magiclink&next=%2Fportfolio%2F${sk.trainee_id}%2Fassignments`, { waitUntil:"domcontentloaded" });
await page.waitForTimeout(4000);
errs.length = 0;
await page.goto(`${BASE}/portfolio/${sk.trainee_id}/assignments/${sk.id}`, { waitUntil:"domcontentloaded" });
await page.waitForTimeout(6000);
console.log("errors on", sk.who.full_name, "Skills:");
errs.forEach(e=>console.log("  ", e));
await b.close();
