import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import fs from "fs";
const env = fs.readFileSync(".env.local", "utf8");
const db = createClient(env.match(/NEXT_PUBLIC_SUPABASE_URL=(.+)/)[1].trim(), env.match(/SUPABASE_SERVICE_ROLE_KEY=(.+)/)[1].trim());
const { data: l } = await db.auth.admin.generateLink({ type:"magiclink", email:"walk-trainer@celtaconnect.com" });
const b = await chromium.launch();
const ctx = await b.newContext({ timezoneId: "Europe/Istanbul" });
const page = await ctx.newPage();
const out = [];
page.on("console", m => out.push(`[${m.type()}] ${m.text()}`));
page.on("pageerror", e => out.push("PAGEERROR " + String(e)));
// log in first, then navigate to the page on its own so hydration is clean
await page.goto(`http://localhost:3000/auth/confirm?token_hash=${l.properties.hashed_token}&type=magiclink&next=%2Ftrainer%2Fassignments`, { waitUntil:"domcontentloaded", timeout: 120000 });
await page.waitForTimeout(15000);
console.log("logged in at:", page.url());
out.length = 0;
await page.goto("http://localhost:3000/trainer/assignments/766201e6-d002-4f07-a41a-d2a4283ca144", { waitUntil:"domcontentloaded", timeout: 120000 });
await page.waitForTimeout(20000);
console.log("landed:", page.url());
console.log("--- console ---");
console.log(out.join("\n").slice(0, 4000) || "(silent)");
await b.close();
