-- The tutor's words about the candidate's task, carried into whichever email
-- goes out -- offer or rejection.
--
-- full-email-specs.md shows this text inside the OFFER email -- "strong on
-- organisation and substance... both analysis items were left blank and that
-- is worth attention early" -- as well as both rejections. Ramy, 2026-08-16:
-- "it will be for everybody, whether it's a reject or acceptance", and it also
-- sits in the application form, so the assessor sees it.
--
-- How it is written (Ramy, same conversation): "a combination of both, the one
-- generated by AI and whatever the tutor decides to edit, add, or delete."
--
-- Which is why this is three columns rather than one. The inventory's rule for
-- the rejections is absolute -- "the centre's reason in the tutor's own words",
-- "human-written, never generated" -- and an AI draft that a tutor accepted
-- without reading would violate it invisibly. Keeping the draft alongside the
-- final text makes the difference checkable: if they are byte-identical,
-- nobody edited anything, and that is a fact worth being able to establish
-- when a candidate challenges a decision.
alter table public.applicants add column if not exists task_feedback text;
alter table public.applicants add column if not exists task_feedback_ai_draft text;
alter table public.applicants add column if not exists task_feedback_edited_by uuid references public.profiles (id) on delete set null;
alter table public.applicants add column if not exists task_feedback_edited_at timestamptz;

comment on column public.applicants.task_feedback is
  'The final text that sends, after the tutor has edited it. Never sent unedited without that being visible -- compare against task_feedback_ai_draft.';
comment on column public.applicants.task_feedback_ai_draft is
  'The AI-generated starting point, kept unchanged. Its purpose is comparison, not display.';
comment on column public.applicants.task_feedback_edited_by is
  'Who last edited the feedback. Null means nobody has touched the draft.';
