-- Ramy, 25 Aug 2026: "I don't want to limit the teachers... it could be a
-- Google doc or a Google slide or a PDF or a PowerPoint or a Word doc...
-- or an image or a screenshot." Google Docs/Slides/Sheets already work today
-- via the Drive-attach flow (slides_url, no file_type needed) --
-- storage_path uploads were the only thing actually limited to pdf/image.
-- Widens the same check constraint 0022_tp_card.sql defined inline (so its
-- name was auto-generated by Postgres, not chosen) -- looked up by table +
-- column rather than assumed by name, so this can't silently leave the
-- old, narrower constraint in place alongside a new one.
do $$
declare
  old_name text;
begin
  select conname into old_name
  from pg_constraint
  where conrelid = 'public.tp_materials'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%file_type%';
  if old_name is not null then
    execute format('alter table public.tp_materials drop constraint %I', old_name);
  end if;
end $$;

alter table public.tp_materials add constraint tp_materials_file_type_check check (file_type in (
  'pdf', 'image', 'pptx', 'docx'
));
