-- Ramy, 28 Aug 2026: "I could keep it structured. Yeah. Structured,
-- worksheet would be good."
--
-- Types each of the 50 UCLES 2018 tasks so the page renders a real
-- worksheet instead of one free-text box per task -- Correct/Not buttons
-- where Cambridge asks which sentences are correct, dropdowns where it asks
-- you to match, a short box per word where it asks about ten words in a
-- list. Hand-written per task against the real question text rather than
-- pattern-matched: several tasks look alike in outline and differ in what
-- they actually ask for.
--
-- Shapes: open | parts | rows_text | rows_choice | rows_choice_text |
-- rows_select | checklist. Answers keep living in
-- pre_course_task_responses.response as JSON (response_kind = 'json'),
-- which is exactly why 0237 made that column free-form -- no migration
-- needed to add a shape later.
alter table public.pre_course_task_items add column if not exists shape jsonb;

update public.pre_course_task_items set shape = '{"kind": "parts", "parts": ["In what context will you be doing the CELTA course?", "Do you know what context you will be teaching in after you finish the course?"]}'::jsonb where task_number = 1 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "parts", "parts": ["Think about why you decided to teach adults.", "Think about what you, as an adult, bring to this learning situation.", "Use those ideas to write down what characterises adult learners."]}'::jsonb where task_number = 2 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "parts", "parts": ["What would you want to find out about a group of learners so that you could plan your lessons?", "How would you find out?"]}'::jsonb where task_number = 3 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 4 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "checklist", "pick": 5, "options": ["has a sense of humour", "has a calm presence", "builds rapport", "is approachable", "knows how to listen well to students", "trusts learners", "is patient", "respects individuality", "gives clear information and feedback", "knows about language and learning", "inspires confidence", "is sensitive to learners as people", "paces lessons to match the learners", "is methodical and well-organised", "plans well", "can be authoritative without being distant", "is always learning and developing", "is enthusiastic and inspires enthusiasm", "is friendly", "is honest", "empathises with the learners", "does not complicate things unnecessarily", "is sensitive to the culture and backgrounds of the learners"]}'::jsonb where task_number = 5 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 6 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_choice_text", "options": ["Correct", "Not"], "text_when": "Not", "text_label": "Write the correct version…", "rows": ["We''ve been looking for you for ages.", "I''ve been to the movies last night.", "He often come late.", "They were waiting by the fountain.", "Can I have a coffee black, please?", "People with 12 items or less can queue here."]}'::jsonb where task_number = 7 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 8 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["Noun", "Pronoun", "Verb", "Modal verb", "Adjective", "Adverb", "Article", "Conjunction", "Preposition", "Determiner"], "rows": ["you", "a", "but", "quite", "abstract", "could", "those", "for", "mean", "plunger"]}'::jsonb where task_number = 9 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_choice", "options": ["Lexical", "Auxiliary"], "rows": ["He watches TV for at least two hours every evening.", "What are you looking for?", "They aren''t going to come.", "What does he want?", "They haven''t been here before.", "He was waiting on the corner."]}'::jsonb where task_number = 10 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_choice", "options": ["Auxiliary", "Lexical"], "rows": ["I had a bad headache yesterday.", "When do you get up each day?", "How long have you been learning English?", "I did it without thinking.", "We do some exercise every morning.", "Have you had them long?", "I was hoping for a quick answer.", "Are they still here?"]}'::jsonb where task_number = 11 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["A. Ability", "B. Logical deduction", "C. Advice", "D. Possibility", "E. Permission"], "rows": ["You should see a doctor as soon as you can.", "You may go now, thank you.", "This letter must be from Frank – he''s the only one who hasn''t written so far.", "I can''t play the piano very well.", "We could go out, but I don''t know if I''m in the mood."]}'::jsonb where task_number = 12 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["base form", "3rd person – present simple tense", "past tense form", "past participle form", "-ing form"], "rows": ["I worked until 7 o''clock last night.", "They''ve been seeing a lot of each other lately.", "She lives not far from here.", "You have to try harder.", "It was handed to me as I was leaving."]}'::jsonb where task_number = 13 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Past form", "Past participle", "Regular or irregular?"], "rows": ["hear", "do", "help", "think", "take", "steal", "go", "drink", "arrive"]}'::jsonb where task_number = 14 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Elements"], "rows": ["I was hoping to see you.", "They might have got home by now.", "We have tried to help.", "They were being questioned at length.", "I saw it coming.", "This time next week you will be lying on a beach."]}'::jsonb where task_number = 15 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Tense name"], "rows": ["I am having a really good time.", "We stopped doing that years ago.", "She lives somewhere near here.", "We had been for a drink before we met him.", "These computers are made in China.", "You will have been here for 2 days by then.", "It happened as I was driving home.", "I have been feeling unwell for a while."]}'::jsonb where task_number = 16 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Time reference"], "rows": ["The sun was shining brightly in the sky. (past progressive)", "They''ll have finished work on the bridge by then. (future perfect simple)", "She''s been working in the garden all morning. (present perfect progressive)", "Have you got a minute? I was wondering whether we could have a word. (past progressive)", "They own most of the land around here. (present simple)"]}'::jsonb where task_number = 17 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "parts", "parts": ["What auxiliary verb is used to create the present progressive?", "What is the form of the lexical verb of the present progressive?"]}'::jsonb where task_number = 18 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Time reference or use"], "rows": ["A: How about going to a movie this evening? / B: I can''t. I''m meeting Judy for a drink.", "A: Where''s Tony? / B: I don''t know where he''s got to. / A: He''s always running late.", "It was late at night… Suddenly, I find I''m walking down the street all on my own…"]}'::jsonb where task_number = 19 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["What''s the problem?"], "rows": ["He''s having a brother and a sister.", "I''m liking this ice cream.", "What are you thinking of your new job?", "This sauce is lacking salt."]}'::jsonb where task_number = 20 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 21 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Identify and describe the problem"], "rows": ["He''s the highest person in the family by more than 2 centimetres.", "I think I''ll go to bed now. I''m feeling a little enervated.", "It is an extremely good essay. The ideas in it are original and pretentious.", "Her grandfather gave her a loving slap on her face.", "Every day I like to go footing after work. It''s good exercise and it helps me to relax."]}'::jsonb where task_number = 22 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Collocation(s) and type"], "rows": ["Not only was he nice, but he was also strikingly handsome.", "After he got up, he made his bed and did some housework.", "It was absolutely fabulous!", "They both really depend on each other.", "Their farewell at the airport was highly emotional.", "She was caught in a vicious circle."]}'::jsonb where task_number = 23 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["A. the music of our voices", "B. giving emphasis to one syllable", "C. an individual sound"], "rows": ["stress", "phoneme", "intonation"]}'::jsonb where task_number = 24 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["A. the word is incomprehensible", "B. the listener might understand ''bin'' when the speaker wanted to say ''pin''", "C. the speaker can sound arrogant and demanding"], "rows": ["an individual sound is mispronounced", "a request is made with very flat intonation", "the wrong syllable is stressed in a word"]}'::jsonb where task_number = 25 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 26 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Which syllable is stressed?"], "rows": ["guarantee", "cavalry", "mechanisation", "language", "retreat", "speculative", "success", "balance", "identity", "articulate (adjective)"]}'::jsonb where task_number = 27 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "parts", "parts": ["Mark the main stress on photograph / photography / photographer / photographic. Why do non-native speakers often have problems with these words?", "Mark the stress in: to record / a record, to increase / an increase, to present / a present, to import / an import. Can you identify a pattern?"]}'::jsonb where task_number = 28 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Where is the /ə/?"], "rows": ["mother", "forget", "announce", "tonight", "notable", "mention", "patrol", "indicative"]}'::jsonb where task_number = 29 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 30 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["Scan reading", "Skim/gist reading", "Intensive/detailed reading", "Reading to infer"], "rows": ["An academic article we need to read for an essay we are writing.", "A telephone directory.", "The editorial of a newspaper on a topic we care about a lot.", "An advertisement for a job that might be suitable."]}'::jsonb where task_number = 31 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 32 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 33 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 34 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["Scan listening", "Skim/gist listening", "Intensive listening", "Listening to infer meaning"], "rows": ["A lecture for a course you are taking at university.", "A sales pitch for a computer that doesn''t really interest you, but you''re at work and can''t walk out.", "Announcements at a train station when you are waiting to hear the time of the next train.", "Instructions from your boss for a new task that is critical for your job.", "An interview with someone famous whose political opinion you would like to find out about.", "A radio programme on a topic that is mildly interesting for you."]}'::jsonb where task_number = 35 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 36 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_choice", "options": ["Successful", "Not successful"], "rows": ["Could I please have a ….? (learner gesticulates, unsure of the word)", "You come my house tonight? (said with rising intonation)", "Yesterday good time. Next week we see, no? (learner smiles)", "A: How long have you been in New Zealand? / B: I stay here 5 weeks."]}'::jsonb where task_number = 37 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_choice", "options": ["Transactional", "Interactional"], "rows": ["You ask a colleague if s/he would mind helping you with something.", "You offer to collect your neighbour''s mail while s/he is away on holiday.", "You comment on the weather to an acquaintance at a bus stop.", "You visit a friend and spend time admiring and talking about his/her garden.", "You participate in a university group tutorial that is useful for an essay you are writing.", "You go out with your boss and other colleagues for a drink after work."]}'::jsonb where task_number = 38 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 39 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_choice", "options": ["Spoken", "Written"], "rows": ["Includes gesture and facial expression to back up the message.", "Uses punctuation to make the content easier to understand.", "Includes hesitation devices and fillers such as ''yeah'', ''umm'', ''ah'' etc.", "The communicator usually gets immediate feedback from the person they are communicating with.", "Usually involves greater planning in advance.", "Uses pauses, stress and intonation to show where ideas begin and end.", "Is spontaneous and planning usually takes place in the moment of communicating.", "Suggests that meaning is static in the communication, although open to interpretation.", "The communicator may never find out what the person he is communicating with thinks of his message.", "Includes headlines, different type sizes and colours to enhance the content.", "Is usually smooth-flowing.", "Involves negotiation of meaning between the communicator and the person they are communicating with."]}'::jsonb where task_number = 40 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["The mistake", "Why the learner made it"], "rows": ["She through the ball hard so it hurt when I court it.", "My brther livs in Swedn.", "However, hard I try it never works.", "first of all he invited me to sit down after that he offered me a coffee I was very surprised by his politeness"]}'::jsonb where task_number = 41 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "parts", "parts": ["Identify the difficulties encountered by learners whose first language does not have a Roman script.", "Suggest some activities teachers can use to help students develop basic writing skills."]}'::jsonb where task_number = 42 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["1. Lesson aims/learning outcomes", "2. Anticipated problems and solutions", "3. Personal aim", "4. Stage", "5. Procedure", "6. Interaction pattern", "7. Stage aim"], "rows": ["a. I''d like to smile more and create a better rapport today.", "b. Students → Students in pairs", "c. By the end of the lesson students will be able to use a range of adjectives to describe someone''s personality.", "d. Teacher hands out text and gives a different set of questions to each group.", "e. Some students may find the pronunciation of several words quite difficult. I must make sure I use lots of repetition.", "f. To get students interested in the topic of the listening text."]}'::jsonb where task_number = 43 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_select", "options": ["a. Encouraging students to expand their vocabulary and find out about new words on their own", "b. Developing students'' ability to read real texts", "c. Giving students work which can be tailored to their individual needs", "d. Developing students'' ability to listen to authentic speech", "e. Finding information on a particular topic area and developing reading skills", "f. Developing students'' language and skills in a structured way and allowing them to review at home", "g. Developing students'' listening skills with specially prepared or real materials", "h. Writing down new words for students to focus on, making form, meaning or pronunciation clear", "i. Showing pre-prepared work on a large screen for clarity"], "rows": ["Published coursebook", "Cassette or CD player", "Newspapers in English", "Internet", "Overhead Projector (OHP)", "Whiteboard", "TV/radio", "Teacher''s own materials", "Dictionaries"]}'::jsonb where task_number = 44 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["Why did the difficulty occur?", "A more effective instruction"], "rows": ["Jot that down.", "I wonder if you''d mind just looking at question number 4 and then if you could just answer it.", "I''d like you to read the text on page 4 and answer the first three, then compare your answers with the person next to you. After that write a short summary of the story and discuss this with your partner.", "Look at the question at the bottom of the page and think about an answer."]}'::jsonb where task_number = 45 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["How would you respond?"], "rows": ["I don''t want to work in a group because I will only learn mistakes from other students.", "I wish you could translate more words into my language.", "Please don''t ask me to work with that student. I don''t like people from her country.", "Could we just talk in class and not use any books?"]}'::jsonb where task_number = 46 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "parts", "parts": ["How would you arrange the classroom (position of desks, chairs, students and teacher)?", "What resources could you use to make the activity more effective?", "What problems about the organisation of the activity could you anticipate?"]}'::jsonb where task_number = 47 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "rows_text", "cols": ["How would you make the difference clear?"], "rows": ["Meaning: slim / thin", "Meaning: to wink / to blink", "Meaning: I used to get up early / I am used to getting up early", "Meaning: nervous / upset", "Meaning: 4 weeks ago / 4 weeks before", "Pronunciation: I do it / I''ll do it", "Pronunciation: read (present tense) / read (past tense)", "Pronunciation: put / putt", "Pronunciation: record (noun) / record (verb)", "Pronunciation: live (verb) / live (something happening now)"]}'::jsonb where task_number = 48 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "parts", "parts": ["Why do you think the reading activity was not successful, and what activity would develop those skills better?", "Why do you think the speaking activity was not successful, and what activity would develop those skills better?"]}'::jsonb where task_number = 49 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
update public.pre_course_task_items set shape = '{"kind": "open"}'::jsonb where task_number = 50 and section_id in (select id from public.pre_course_task_sections where source = 'cambridge');
